config/routes.rb
Rails.application.routes.draw do
  resources :resumelinks

  resources :profiles

  resources :addresses

  resources :resumes

  resources :registrations

  resources :contacts

  resources :telephones

  resources :emails

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/resumelink.rb
class Resumelink < ActiveRecord::Base
  belongs_to :user
  belongs_to :profile
  validates_formatting_of :resumelink, using: :url
end

app/controllers/resumelinks_controller.rb
class ResumelinksController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_resumelink, only: [:show, :edit, :update, :destroy]

  # GET /resumelinks
  # GET /resumelinks.json
  def index
    @resumelinks = Resumelink.all
  end

  # GET /resumelinks/1
  # GET /resumelinks/1.json
  def show
  end

  # GET /resumelinks/new
  def new
    @resumelink = Resumelink.new
  end

  # GET /resumelinks/1/edit
  def edit
  end

  # POST /resumelinks
  # POST /resumelinks.json
  def create
    @resumelink = Resumelink.new(resumelink_params)
    @resumelink.user = current_user

    respond_to do |format|
      if @resumelink.save
        format.html { redirect_to @resumelink, notice: 'Resumelink was successfully created.' }
        format.json { render :show, status: :created, location: @resumelink }
      else
        format.html { render :new }
        format.json { render json: @resumelink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumelinks/1
  # PATCH/PUT /resumelinks/1.json
  def update
    respond_to do |format|
      if @resumelink.update(resumelink_params)
        format.html { redirect_to @resumelink, notice: 'Resumelink was successfully updated.' }
        format.json { render :show, status: :ok, location: @resumelink }
      else
        format.html { render :edit }
        format.json { render json: @resumelink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumelinks/1
  # DELETE /resumelinks/1.json
  def destroy
    @resumelink.destroy
    respond_to do |format|
      format.html { redirect_to resumelinks_url, notice: 'Resumelink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resumelink
      @resumelink = Resumelink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resumelink_params
      params.require(:resumelink).permit(:resumelink, :default_resume_format, :show_profile, :show_resume, :download_automatically, :user_id, :profile_id)
    end
end

app/helpers/resumelinks_helper.rb
module ResumelinksHelper
end

app/views/resumelinks/_form.html.erb
<%= form_for(@resumelink) do |f| %>
  <% if @resumelink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resumelink.errors.count, "error") %> prohibited this resumelink from being saved:</h2>

      <ul>
      <% @resumelink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resumelink %><br>
    <%= f.text_field :resumelink %>
  </div>
  <div class="field">
    <%= f.label :default_resume_format %><br>
    <%= f.text_field :default_resume_format %>
  </div>
  <div class="field">
    <%= f.label :show_profile %><br>
    <%= f.check_box :show_profile %>
  </div>
  <div class="field">
    <%= f.label :show_resume %><br>
    <%= f.check_box :show_resume %>
  </div>
  <div class="field">
    <%= f.label :download_automatically %><br>
    <%= f.check_box :download_automatically %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumelinks/edit.html.erb
<h1>Editing resumelink</h1>

<%= render 'form' %>

<%= link_to 'Show', @resumelink %> |
<%= link_to 'Back', resumelinks_path %>

app/views/resumelinks/index.html.erb
<h1>Listing resumelinks</h1>

<table>
  <thead>
    <tr>
      <th>Resumelink</th>
      <th>Default resume format</th>
      <th>Show profile</th>
      <th>Show resume</th>
      <th>Download automatically</th>
      <th>User</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumelinks.each do |resumelink| %>
      <tr>
        <td><%= resumelink.resumelink %></td>
        <td><%= resumelink.default_resume_format %></td>
        <td><%= resumelink.show_profile %></td>
        <td><%= resumelink.show_resume %></td>
        <td><%= resumelink.download_automatically %></td>
        <td><%= resumelink.user %></td>
        <td><%= resumelink.profile %></td>
        <td><%= link_to 'Show', resumelink %></td>
        <td><%= link_to 'Edit', edit_resumelink_path(resumelink) %></td>
        <td><%= link_to 'Destroy', resumelink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resumelink', new_resumelink_path %>

app/views/resumelinks/new.html.erb
<h1>New resumelink</h1>

<%= render 'form' %>

<%= link_to 'Back', resumelinks_path %>

app/views/resumelinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resumelink:</strong>
  <%= @resumelink.resumelink %>
</p>

<p>
  <strong>Default resume format:</strong>
  <%= @resumelink.default_resume_format %>
</p>

<p>
  <strong>Show profile:</strong>
  <%= @resumelink.show_profile %>
</p>

<p>
  <strong>Show resume:</strong>
  <%= @resumelink.show_resume %>
</p>

<p>
  <strong>Download automatically:</strong>
  <%= @resumelink.download_automatically %>
</p>

<p>
  <strong>User:</strong>
  <%= @resumelink.user %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @resumelink.profile %>
</p>

<%= link_to 'Edit', edit_resumelink_path(@resumelink) %> |
<%= link_to 'Back', resumelinks_path %>