config/routes.rb
Rails.application.routes.draw do
  resources :resumelinks

  resources :profiles

  resources :addresses

  resources :resumes

  resources :registrations

  resources :contacts

  resources :telephones

  resources :emails

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/telephone.rb
class Telephone < ActiveRecord::Base
  belongs_to :profile
  belongs_to :contact
  belongs_to :user
  validates_formatting_of :number, using: :us_phone
end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_telephone, only: [:show, :edit, :update, :destroy]

  # GET /telephones
  # GET /telephones.json
  def index
    @telephones = Telephone.all
  end

  # GET /telephones/1
  # GET /telephones/1.json
  def show
  end

  # GET /telephones/new
  def new
    @telephone = Telephone.new
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)
    @telephone.user = current_user

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to @telephone, notice: 'Telephone was successfully created.' }
        format.json { render :show, status: :created, location: @telephone }
      else
        format.html { render :new }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telephones/1
  # PATCH/PUT /telephones/1.json
  def update
    respond_to do |format|
      if @telephone.update(telephone_params)
        format.html { redirect_to @telephone, notice: 'Telephone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telephone }
      else
        format.html { render :edit }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone.destroy
    respond_to do |format|
      format.html { redirect_to telephones_url, notice: 'Telephone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telephone_params
      params.require(:telephone).permit(:number, :non_us_number, :profile_id, :type, :do_not_call, :do_not_display, :contact_id, :user_id)
    end
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/telephones/_form.html.erb
<%= form_for(@telephone) do |f| %>
  <% if @telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telephone.errors.count, "error") %> prohibited this telephone from being saved:</h2>

      <ul>
      <% @telephone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :non_us_number %><br>
    <%= f.text_field :non_us_number %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :do_not_call %><br>
    <%= f.check_box :do_not_call %>
  </div>
  <div class="field">
    <%= f.label :do_not_display %><br>
    <%= f.check_box :do_not_display %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/telephones/edit.html.erb
<h1>Editing telephone</h1>

<%= render 'form' %>

<%= link_to 'Show', @telephone %> |
<%= link_to 'Back', telephones_path %>

app/views/telephones/index.html.erb
<h1>Listing telephones</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Non us number</th>
      <th>Profile</th>
      <th>Type</th>
      <th>Do not call</th>
      <th>Do not display</th>
      <th>Contact</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.number %></td>
        <td><%= telephone.non_us_number %></td>
        <td><%= telephone.profile %></td>
        <td><%= telephone.type %></td>
        <td><%= telephone.do_not_call %></td>
        <td><%= telephone.do_not_display %></td>
        <td><%= telephone.contact %></td>
        <td><%= telephone.user %></td>
        <td><%= link_to 'Show', telephone %></td>
        <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
        <td><%= link_to 'Destroy', telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telephone', new_telephone_path %>

app/views/telephones/new.html.erb
<h1>New telephone</h1>

<%= render 'form' %>

<%= link_to 'Back', telephones_path %>

app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @telephone.number %>
</p>

<p>
  <strong>Non us number:</strong>
  <%= @telephone.non_us_number %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @telephone.profile %>
</p>

<p>
  <strong>Type:</strong>
  <%= @telephone.type %>
</p>

<p>
  <strong>Do not call:</strong>
  <%= @telephone.do_not_call %>
</p>

<p>
  <strong>Do not display:</strong>
  <%= @telephone.do_not_display %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @telephone.contact %>
</p>

<p>
  <strong>User:</strong>
  <%= @telephone.user %>
</p>

<%= link_to 'Edit', edit_telephone_path(@telephone) %> |
<%= link_to 'Back', telephones_path %>