config/routes.rb
Rails.application.routes.draw do
  resources :resumelinks

  resources :profiles

  resources :addresses

  resources :resumes

  resources :registrations

  resources :contacts

  resources :telephones

  resources :emails

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  belongs_to :profile
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)
    @resume.user = current_user

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:filename, :format, :generated_by, :is_approved, :is_flagged, :is_current, :version, :user_id, :profile_id, :is_deleted)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :generated_by %><br>
    <%= f.text_field :generated_by %>
  </div>
  <div class="field">
    <%= f.label :is_approved %><br>
    <%= f.check_box :is_approved %>
  </div>
  <div class="field">
    <%= f.label :is_flagged %><br>
    <%= f.check_box :is_flagged %>
  </div>
  <div class="field">
    <%= f.label :is_current %><br>
    <%= f.check_box :is_current %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.number_field :version %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :is_deleted %><br>
    <%= f.check_box :is_deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Format</th>
      <th>Generated by</th>
      <th>Is approved</th>
      <th>Is flagged</th>
      <th>Is current</th>
      <th>Version</th>
      <th>User</th>
      <th>Profile</th>
      <th>Is deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.filename %></td>
        <td><%= resume.format %></td>
        <td><%= resume.generated_by %></td>
        <td><%= resume.is_approved %></td>
        <td><%= resume.is_flagged %></td>
        <td><%= resume.is_current %></td>
        <td><%= resume.version %></td>
        <td><%= resume.user %></td>
        <td><%= resume.profile %></td>
        <td><%= resume.is_deleted %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @resume.filename %>
</p>

<p>
  <strong>Format:</strong>
  <%= @resume.format %>
</p>

<p>
  <strong>Generated by:</strong>
  <%= @resume.generated_by %>
</p>

<p>
  <strong>Is approved:</strong>
  <%= @resume.is_approved %>
</p>

<p>
  <strong>Is flagged:</strong>
  <%= @resume.is_flagged %>
</p>

<p>
  <strong>Is current:</strong>
  <%= @resume.is_current %>
</p>

<p>
  <strong>Version:</strong>
  <%= @resume.version %>
</p>

<p>
  <strong>User:</strong>
  <%= @resume.user %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @resume.profile %>
</p>

<p>
  <strong>Is deleted:</strong>
  <%= @resume.is_deleted %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>